name: Cheeseria App CICD-Workflow

on:
    push:
        branches: [main]
    pull_request:
        branches: ["main"]

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm install 
      - name: run client unit tests
        run: npm test:client:unit
      - name: run server unit tests
        run: npm test:server:unit
      - name: run e2e tests
        working-directory: ./e2e
        run: npm test
      - name: build
        run: npm run build
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_KEY }}
          export_default_credentials: true
      - name: Configure docker
        run: |
          gcloud auth configure-docker
      - name: Build and push image
        run: |
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }} 
            gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/cheeseria
            gcloud config set run/region australia-southeast1
      - name: Deploy service to Cloud Run
        uses: stefda/action-cloud-run@1.0.0
        with:
          working_directory: .
          service_key: ${{ secrets.SERVICE_KEY }}
          project: ${{ secrets.GCP_PROJECT_ID }}
          registry: gcr.io
          region: australia-southeast1

