name: Cheeseria App CICD-Workflow

on:
    push:
        branches: ["main"]

jobs:
  deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Setup Google Cloud Credential'
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}  
      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Configure docker
        run: |
          gcloud auth configure-docker
      - name: Build and push image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/cheeseria
      - name: Deploy to cloud run
        run: |
          gcloud config set run/region australia-southeast1
          gcloud run deploy pz-cheeseria-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cheeseria
    
